### ISSUE TITLE
[EPIC] Getting LAA fee calculator live

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#138]
## Background

We have been working with the [LAA fee calculator](https://github.com/ministryofjustice/laa-fee-calculator/tree/develop) team as an early user on the platform. The team needs to get their service into live. We are going to run this on a live cluster on the cloud platform.

The application is very suitable to an early production service. It is stateless, does not make use of third party resources (e.g. AWS resources), has good fall back options in case of outages, is well supported by a team that we have been working with   

## Proposed user journey

- Team creates an app
- Team wants app to go live
- Team creates a bunch of Kubernetes bits that give them pipelines and enviroments 

## Approach

We are going to set up a strike team to work with LAA fee calc team directly to: 

a) get the app running on the `live-0` cluster in an kubernetes friendly way (there is a little bit of tidy up from our current work)
b) make sure the `live-0` cluster is set up for production
c) test some recovery procedures

The rest of the team will work on other operational stories that we will release to the `live-0` cluster as they get done.  

## Stories in this epic

- [x] Figure out how to work with LAA fee calculator team
- [ ] Draw a diagram of the app and cluster architecture (to agree with LAA team)
- [x] Create namespace and permissions for LAA fee calculator live env (and any other envs)
- [x] Work out support process for LAA fee calculator team
- [x] Work with LAA fee calculator team to create deployment workflow
- [x] Work with LAA fee calculator team to define app deployment in kubernetes primitives
- [x] Upgrade `live-0` cluster instances to C4 class
- [x] Work with LAA fee calculator team to test postgres failure and recovery
- [x] Work with LAA fee calculator team to test app failure and recovery
- [ ] Set up DNS for the app (and document)
- [x] Create and agree a release plan

Other things:
- [x] Create `test-0` cluster 
- [ ] Test and document recovering the app to a new cluster 

## Questions / Assumptions

We listed the following assumptions, we'll tick the box when they are agreed:

- [x] Cloud platform and the LAA fee calc team will work together to define processes for deploying and running the app
- [x] We will run the app on `live-0` cluster
- [x] The LAA fee calc team will "bring their own monitoring" to begin with
- [x] We understand (as a team) that there is a live service on the `live-0` cluster 
- [x] The app needs no AWS resources (right now)
- [x] The app is stateless 
- [x] The team will deploy the app from CircleCI
- [x] The app is exposing an HTTP API (ie. not websockets, UDP, etc)
- [x] We will run 3 nodes in the `live-0` cluster
- [x] The data source that LAA fee calc team are using is only updated periodically

We also have the following questions:

- How do we work with LAA fee calc team?
- What is our support process for Kubernetes?
- What is the postgres <--> app architecture (separate pods? multiple postgres instances?)
- How does the team update LAA fee calc schema?

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kcbotsh** [comment]
closing as no further work required until team return with any other requests. (support contained in other tickets
