### ISSUE TITLE
[EPIC]: We can recover laa fee calc to a new cluster

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#192]
## Background

We are putting the [laa-fee-caculator] app live on the `live-0` cluster. Whilst we expect cluster failures to be infrequent we want to be able to recover from a cluster failing. The first technique we will use for this kind of disaster recovery is to build a new cluster and deploy the app onto that cluster. In this epic we will test that recovery process with the aim of getting it so that we can recover from cluster failure in under 1 hour.

To do this we will need to improve our cluster creation process so that it is better automated, easier to run and well documented. Once we have done that we will run some recovery exercises so that we can measure how long it takes us to recover.  

## Proposed user journey

- Alert goes off that indicates a cluster is in a bad state
- Team member gets alert, investigates
- Team member decides to recover to a new cluster
- Team member goes to documentation in GitHub to find out how to create a new cluster
- ...follows the docs (runs terraform, kops and any other scripts etc)
- New cluster is up in <1 hr
- Team member deploys app onto new cluster, switches over DNS
- Service is recovered

## Approach

We will break out the cluster creation process and make sure it:

- is clearly documented
- can setup all of the services that the cluster needs (e.g. kuberos, ingress etc)
- is largely automated (with clearly noted caveats and instructions in the docs)
- has been run by everyone in the team

## Sub issues

#171 #180 #164 #166 

## Definition of done

- [ ] There is documentation that covers how to create a new cluster in the `cloud-platform` AWS account
- [ ] Everyone in the team can create a cluster 
- [ ] We can create a cluster and deploy an app to it in under 1 hr

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
