### ISSUE TITLE
Create a new environment skeleton with a script

### ISSUE THREAD

**Issue by alkar** [ministryofjustice/cloud-platform#205]
## Background

Creating a new environment currently requires that a user to manually populate a directory with files which are largely the same across namespaces. We would like to streamline this process by introducing a script that does most of the work.

## Proposed user journey

As a user, from the environments repository, I want to be able to create a new environment by using a script, eg:
```
./create-env <cluster> <env-name> <github-team>
```
This script will then create the proper directory structure with the default YAML configuration already in place.

I can then use that to raise a pull request against the master branch.

## Approach

Try to automate as much as possible from: https://github.com/ministryofjustice/cloud-platform-user-docs/blob/master/01-getting-started/003-env-create.md

## Questions / Assumptions

Depends on #206
Depends on #207
Depends on #208

## Definition of done

- [ ] there is an environment creation script in the environments repository that can create an environment with default configuration
- [ ] the script creates the environment's directory which includes:
  - [ ] `00-namespace.yaml`
  - [ ] `01-networkpolicies.yaml` (see #206)
  - [ ] `02-resourcequotas.yaml` (see #208)
  - [ ] `03-limitranges.yaml`  (see #207)
  - [ ] `05-rbac.yaml` with configuration for the GitHub team
- [ ] tested by the reviewer

## Reference
https://github.com/ministryofjustice/cloud-platform-user-docs/blob/master/01-getting-started/003-env-create.md

**Comment by alkar** [comment]
Does Helm provide a way to enter these values interactively? I feel that would be even better in terms of user experience?
(we could even use a bit of tf with templates)
