### ISSUE TITLE
Moving Correspondence Staff Tool to Kubernetes

### ISSUE THREAD

**Issue by misaka** [ministryofjustice/cloud-platform#299]
## Background

The Correspondence Tool is looking to move to the new Kubernetes platform for a few reasons, such as on-going problems with the current deploy system and the need to be well-positioned for moving to maintenance mode. To avoid / add-to confusion, this app is also known as Answer Tool and, more officially, Track-A-Query. The current production URL is http://track-a-query.dsd.io/

Some more info about the service:

- app is stateless, relying on AWS service for persistent storage:
  - RDS (Postgres)
  - ECS (Redis)
  - S3
- uses 3 Docker images:
  - the primary web-app, exposing endpoints for HTTP and HTTPS
  - 2 containers for triggered / scheduled background jobs
- all images created from the `Dockerfile` in the repo, with a `docker-compose.yml` to define the running environment
- is in use across the MoJ, but still considered beta and the primary users are dual-running with their original system
 
## Approach

CT team will follow the Cloud Platforms guide to creating an environment and deployment definition, with the aid of Cloud Platforms. The CT Team will then integrate with existing CI solution (Jenkins + semaphore CI) or migrate to a new one as required.

### Create Environment

- [ ] Install / setup kubectl on dev machines.
- [ ] Create new environment definition.
- [ ] Create PR and get the new environment merged.
- [ ] (Optional) Setup Elastic Container Register (ECR) repository (vs the old registry.service.dsd.io which may be deprecated at some point)
- [ ] Define required resources (cpus, memory, etc)
- [ ] Create YAML deployment definition
- [ ] Integrate with CI

## Definition of done

Application is deployable using Kubernetes and automated so that:

- [ ] When a PR is merged a build is triggered and the resulting images are deployed to dev.
- [ ] The same images are then deployable to staging and production, and is automated.
- [ ] Deployment is a one-click affair so does not require processing by dev team.

## Reference

- [Cloud Platform user guide](https://ministryofjustice.github.io/cloud-platform-user-docs)
- [Cloud Platform environments definitions](https://github.com/ministryofjustice/cloud-platform-environments/tree/master/namespaces/cloud-platform-live-0.k8s.integration.dsd.io)
- [Example Kubernetes stateless deploy file](https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/)
- [LAA Fee Calculator deploy definitions](https://github.com/ministryofjustice/laa-fee-calculator/tree/dd_dk_sqlite_and_k8s/kubernetes_deploy)
- [LAA Fee Calculator Circle CI config](https://github.com/ministryofjustice/laa-fee-calculator/blob/dd_dk_sqlite_and_k8s/.circleci/config.yml)
----
[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
