### ISSUE TITLE
Runbook Update: Calico checklist

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#4558]
## Background

Runbook:
https://runbooks.cloud-platform.service.justice.gov.uk/calico.html#calico-checklist-before-an-upgrade

Now that we've moved from AWS deprecated Calico charts to Tigera Operator:
https://github.com/ministryofjustice/cloud-platform-terraform-tigera-calico

we need to review this runbook and update as necessary.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by Matt-Alinosn** [comment]
This was done.
