### ISSUE TITLE
Replace kubectl Terraform provider

### ISSUE THREAD

**Issue by sj-williams** [ministryofjustice/cloud-platform#5380]
## Background
During testing of kubernetes 1.27 upgrade process, we have incovered issues with terraform apply at components level regarding read of k8s manifest objects. This has been tracked down to a bug with our `gavinbunney/kubectl` terraform provider which is used extensively in our components build / modules.

More details in ticket: 
https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=55823671

This provider seems effectively abandoned (2 years since last update), and a fork exists which addresses the bug we have encountered as well as continuing the work of maintaining the provider codebase.

https://github.com/alekc/terraform-provider-kubectl

## TODO

Switch out all existing kubectl provider configs to use `alekc` provider, and test:

- new cluster builds at 1.26 / 1.27
- existing 1.26 cluster upgrade in place

## Communicate changes

- [ ] post for #cloud-platform-update
- [ ] Weeknotes item
- [ ] Show the Thing/P&A All Hands/User CoP
- [ ] Announcements channel

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green
- [ ] prepare demo for the team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sj-williams** [comment]
Modules with kubectl provider:

- [ ] github.com/ministryofjustice/cloud-platform-terraform-concourse
- [ ] github.com/ministryofjustice/cloud-platform-terraform-certmanager
- [ ] github.com/ministryofjustice/cloud-platform-terraform-external-dns
- [ ] github.com/ministryofjustice/cloud-platform-terraform-ingress-controller
- [ ] github.com/ministryofjustice/cloud-platform-terraform-logging
- [ ] github.com/ministryofjustice/cloud-platform-terraform-monitoring
- [ ] github.com/ministryofjustice/cloud-platform-terraform-gatekeeper
- [ ] github.com/ministryofjustice/cloud-platform-terraform-kuberhealthy

**Comment by timckt** [comment]
- [ ] github.com/ministryofjustice/cloud-platform-terraform-tigera-calico
