### ISSUE TITLE
User can add AWS resources to their application

### ISSUE THREAD

**Issue by kalbir** [ministryofjustice/cloud-platform#62]
## Background

Many (if not most) applications at MoJ use some AWS services as part of their application. Some of the services that applications use include S3, SQS, RDS and others. When a team deploy their application to the cloud platform they will need to be able to consume these resources on AWS. 

The way we are thinking of getting teams access to these resources is to have a file in their environment directory in the environment creation repo that defines the resources they want to use by referencing terraform modules that we host. 

So if a team wants an S3 bucket they will reference a terraform module that we have produced and provide the necessary config for their specific instance. 

## Proposed user journey

User needs an S3 bucket for their application.
_Assuming that they have already created a namespace and deployed an app to it._ 

* User goes to the documentation to find out how to add S3
* User goes to their environment definition in the appropriate repo
* They add a file in that repo that references a terraform module to create an S3 bucket and lets them provide some specific application/environment specific configuration. 

* That runs a pipeline that uses the terraform module to create an S3 bucket for them and gives them back an access token to connect to that bucket.  

* They add the access token as a secret to their application and use it in their app to connect to the bucket

## Approach

Kerin: I'm not keen on users editing plain Terraform resources directly, but having them reference a TF module and provide some args seems totally fine to me - it allows us to control what attributes of AWS resources they're able to configure themselves. e.g:

module "laa_fees_database" {
source = "ministryofjustice/cloud-platforms-rds-terraform"
db_name = "laa_fees"
engine = "postgres"
app_env = "laa-fees-staging"
}

That module can encapsulate RDS itself, any required VPC/SG things, and the Kubernetes secret that holds the connection details.

## Sub- issues

#37 #38 #65 #66 #67 #68 #69 #70 #71 #72 #73 #74 #75 

## Questions/Assumptions

* We will have to provide the connection string/bucket name/resource identifier as an environment variable in the namespace in Kubernetes
* Users write terraform files with the structure above -- they reference a module that contains the majority of the terraform code
They can be either public modules or ones that we write ourselves, whatever works best
We want to give people a small range of parameters that they can override

## Definition of done

- [ ] Documentation for users on how to add the resources to their application
- [ ]  Demo to and sign off from product manager
- [ ] Documentation for cloud platform team explaning how this works (architecture diagram)
- [ ] Template app updated to use this method of requesting an AWS resource bucket
- [ ] Works for S3
- [ ] Works for SNS
- [ ] Works for SQS
- [ ] Works for RDS

**Comment by kalbir** [comment]
Diagram from our planning session... not sure how useful this will be.
![user-journey-add-s3](https://user-images.githubusercontent.com/3952074/40439457-e3feb59e-5eb2-11e8-8927-5a6c62476967.jpg)
