### ISSUE TITLE
Live 1 EPIC

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#771]
## Background

We created a new Live 1 cluster. Teams already migrated to Live 0 would need to migrate again to the new cluster but any new services created will go to Live 1 when ready.

We have a number of teams who are ready to migrate to Live 1 is not quite ready. To save teams having to do an extra migration we are prioritising the readiness of Live 1.

## Proposed user journey

Users will be able to migrate production services to Live 1 cluster.

## Approach

The following activities need to take place:
- Apply AWS baseline security (Sid)
- Pod security policies working in Live 1 cluster
- Concourse pipeline (environments) (get - environments) (Plan)
- Change modules to eu-west-2 & live 1 - Paramatize (Mourad)
- Monitoring - Custom alerts & terraform install
- Terraform 'creating domains'
- Cluster agnostic CNAME cloud-platform.servioce.justice.gov.uk

## Which part of the user docs does this impact

N/A

## Questions / Assumptions

It is possible that new stories might emerge as part of this work. Stories can be linked to this EPIC.

## Definition of done

- [x] Apply AWS baseline security (Sid)
- [x] Pod security policies working in Live 1 cluster
- [x] Concourse pipeline (environments) (get - environments) (Plan)
- [x] Change modules to eu-west-2 & live 1 - Paramatize (Mourad)
- [x] Monitoring - Custom alerts & terraform install
- [x] Terraform 'creating domains'
- [x] Cluster agnostic CNAME cloud-platform.servioce.justice.gov.uk

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jasonBirchall** [comment]
All tasks complete for this Epic.
