### ISSUE TITLE
Create new repo for PD/Pingdom Terraform

### ISSUE THREAD

**Issue by sablumiah** [ministryofjustice/cloud-platform#811]
## Background

Currently all terraform for PD/Pingdom resides in cloud-platform-terraform-ops.
This also has terraform for sensu and all TD systems and shared state file in AWS MOJ DSD account.

This will mean we do not have to manage and move old application terraform and also be in line with new standards we have created for terraform setup.

## Proposed user journey

Create a new repo and move new alerts only including new bucket for state-file in the AWS CP account. 

- [ ] create new bucket in AWS CP and new github repo
- [ ] Setup both PD and Pingdom providers (use tools docker image) 
- [ ] Move new cluster alerts and PD setup to new setup

**Comment by AntonyBishop** [comment]
Discussed with Sablu. Feeling in that some of this might have been done, but we don't have a view of how much more needs to be done. Suggest taking this one into a planning session to be broken down into smaller stories.

**Comment by AntonyBishop** [comment]
No longer required.
