### ISSUE TITLE
Centralised Runbooks for the Cloud Platform

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#847]
## Background

We have started documenting runbook content in a multitude of places e.g. guides, readme files. It's becoming increasing difficult to manage and we need to ensure that runbooks are kept up to date so that we can operate the service.

Previously we had Ops Manual, and later Confluence to centralise out runbooks. We want to find a suitable alternative to bring all our runbook material together so it can be referenced in one place.

## Approach

1. Determine how and where we centralise runbooks
2. Research and discuss options with team
3. Implement a solution

## Which part of the user docs does this impact

N/A

## Definition of done

- [x] We understand what needs to be included in runbooks
- [x] Determine how we will centralise runbooks
- [x] First iteration of centralised runbook

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
