### ISSUE TITLE
Upgrade to Terraform 0.12

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cloud-platform#994]
Placeholder

## Questions / Assumptions

- We need to catalogue all our Terraform to understand what would be impacted by upgrade.
- Prioritise code to be changed
- Need to determine approach (big bang change)

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] smoke tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
